### ISSUE TITLE
package versions

### ISSUE THREAD

**Issue by liyenhsu** [jshang123/G-Bert#7]
Hi,

Can you kindly provide the required versions of the following packages in order to run your code?
```
torch-scatter
torch-sparse
torch-cluster
torch-spline-conv
```
I'm using `torch_geometric==1.0.3` as the README suggests, but I still get a lot of errors due to either `torch-scatter` or `torch-sparse`

Thanks!

**Comment by Duchp1997** [comment]
I also have some problem at the package `torch-sctter`,when I trained the code _run-gbert.py_ with graph.

here are code part:

`

Traceback (most recent call last):

  File "/home/dcp/.pycharm_helpers/pydev/pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dcp/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dcp/G-Bert/Codes/run_gbert.py", line 509, in <module>
    main()
  File "/home/dcp/G-Bert/Codes/run_gbert.py", line 400, in main
    epoch=global_step)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/predictive_models.py", line 157, in forward
    _, bert_pool = self.bert(input_ids, token_types_ids)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/bert_models.py", line 312, in forward
    x = self.embedding(x, token_type_ids)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/graph_models.py", line 291, in forward
    input_ids) + self.type_embedding(input_types)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/graph_models.py", line 265, in forward
    [self.special_embedding, self.rx_embedding(), self.dx_embedding()], dim=0)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/graph_models.py", line 59, in forward
    emb = self.g(self.g(emb, self.edges1.to(emb.device)),
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcp/G-Bert/Codes/graph_models.py", line 218, in forward
    return self.propagate('add', edge_index, x=x, num_nodes=x.size(0))
  File "/home/dcp/G-Bert/Codes/graph_models.py", line 117, in propagate
    out = scatter_(aggr, out, edge_index[0], dim_size=size)
  File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
    out = op(src, index, 0, None, dim_size, fill_value)

RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)
`

while I looked up the original code, `op(src, index, 0, None, dim_size, fill_value)`  did have 6 argument. I wonder if there is the problem with the package code version.

**Comment by Gkunnan97** [comment]
> 
> 
> I also have some problem at the package `torch-sctter`,when I trained the code _run-gbert.py_ with graph.
> 
> here are code part:
> 
> `
> 
> Traceback (most recent call last):
> 
> File "/home/dcp/.pycharm_helpers/pydev/pydevd.py", line 1415, in _exec
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/home/dcp/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/home/dcp/G-Bert/Codes/run_gbert.py", line 509, in
> main()
> File "/home/dcp/G-Bert/Codes/run_gbert.py", line 400, in main
> epoch=global_step)
> File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/dcp/G-Bert/Codes/predictive_models.py", line 157, in forward
> _, bert_pool = self.bert(input_ids, token_types_ids)
> File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/dcp/G-Bert/Codes/bert_models.py", line 312, in forward
> x = self.embedding(x, token_type_ids)
> File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/dcp/G-Bert/Codes/graph_models.py", line 291, in forward
> input_ids) + self.type_embedding(input_types)
> File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/dcp/G-Bert/Codes/graph_models.py", line 265, in forward
> [self.special_embedding, self.rx_embedding(), self.dx_embedding()], dim=0)
> File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl result = self.forward(*input, **kwargs) File "/home/dcp/G-Bert/Codes/graph_models.py", line 59, in forward emb = self.g(self.g(emb, self.edges1.to(emb.device)), File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl result = self.forward(*input, **kwargs) File "/home/dcp/G-Bert/Codes/graph_models.py", line 218, in forward return self.propagate('add', edge_index, x=x, num_nodes=x.size(0)) File "/home/dcp/G-Bert/Codes/graph_models.py", line 117, in propagate out = scatter_(aggr, out, edge_index[0], dim_size=size) File "/home/dcp/anaconda3/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
> out = op(src, index, 0, None, dim_size, fill_value)
> 
> RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)
> `
> 
> while I looked up the original code, `op(src, index, 0, None, dim_size, fill_value)` did have 6 argument. I wonder if there is the problem with the package code version.

same error and I delete  parameter "fill_value" in "torch_geometric/utils/scatter.py", Line 28 "out = op(src, index, 0, None, dim_size, fill_value)". Then the code works, But i am not sure whether this change has inference of the results.
