### ISSUE TITLE
Ontology Embedding

### ISSUE THREAD

**Issue by jane-pyc** [jshang123/G-Bert#8]
您好，请问公式3的Stage 1 表述是什么呢？
没有在您的论文中看到。
代码复现时，这里出现了维度匹配的错误。

**Comment by eh58** [comment]
我也遇到了同样的问题：
Traceback (most recent call last):
  File "run_gbert.py", line 492, in <module>
    main()
  File "run_gbert.py", line 488, in main
    test(task=0)
  File "run_gbert.py", line 472, in test
    input_ids, dx_labels=dx_labels, rx_labels=rx_labels)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/predictive_models.py", line 157, in forward
    _, bert_pool = self.bert(input_ids, token_types_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/bert_models.py", line 312, in forward
    x = self.embedding(x, token_type_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 292, in forward
    input_ids) + self.type_embedding(input_types)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 266, in forward
    [self.special_embedding, self.rx_embedding(), self.dx_embedding()], dim=0)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 59, in forward
    emb = self.g(self.g(emb, self.edges1.to(emb.device)),
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 219, in forward
    return self.propagate('add', edge_index, x=x, num_nodes=x.size(0))
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 116, in propagate
    out = self.message(*message_args)
  File "/content/drive/MyDrive/Colab Notebooks/Multimodal/G-Bert/code/graph_models.py", line 223, in message
    alpha = (torch.cat([x_i, x_j], dim=-1) * self.att).sum(dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 2 but got size 1 for tensor number 1 in the list.

**Comment by pd-illinois** [comment]
@eh58 : Were you able to fix this issue. I have the same issue with the repo.
